language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t connorethan/docker-react . 

# These commands will be run when travis starts testing 
# and if any of these return a status code other than 0 tests fail
# -e is for environment variables to set in container
script:
  - docker run -e CI=true connorethan/docker-react npm run test